### ISSUE TITLE
Check licensing

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#1]
We are using several libraries which I'm not quite sure of how the licensing is handled. Specifically, the `build.gradle` file is interesting.

**Comment by JonasGroeger** [comment]
Add it to the technology description (as a columns).

**Comment by BujakiAttila** [comment]
I am starting to look up the licenses for the used libraries.

**Comment by BujakiAttila** [comment]
Spring Framework - [Apache License v2.0](http://www.apache.org/licenses/LICENSE-2.0)
Java SE (7u79) - [Oracle Binary Code License (BCL)](http://www.oracle.com/technetwork/java/javase/terms/license/index.html)
jQuery (2.1.3) - [MIT license](http://opensource.org/licenses/MIT)
Selenium (2.45.0) - [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0)
Spring Test MVC HtmlUnit (1.00 M1) -  [Apache License v2.0](http://www.apache.org/licenses/LICENSE-2.0)
JUnit (4.12)  - [Eclipse Public License 1.0](http://junit.org/license.html)
Hibernate ORM (4.3.9) - [LGPL V2.1](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html)
PostgreSQL (9.4.1) - [PostgreSQL Licence](http://opensource.org/licenses/postgresql)
Tomcat 7.0.61 - [Apache License v2.0](http://www.apache.org/licenses/LICENSE-2.0)

**Comment by JonasGroeger** [comment]
They all are fine with using them in commercial work. Most of them require us to include their license and a copyright (which is fine, I guess).
