### ISSUE TITLE
Review German localization messages

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#106]
A native German speaker should review the German messages, so we can be sure that it is consistent and acceptable.

**Comment by JonasGroeger** [comment]
Will do that today.

**Comment by BujakiAttila** [comment]
:+1:

**Comment by BujakiAttila** [comment]
Legen-Dale and JonasGroeger checked it. I am going to close this issue, since the related file was reviewed twice.

**Comment by sutard** [comment]
Hi All,

I just tried to fill in the questionnaire from the Client side, and whenever I hit the edit button at the bottom of the form, I was redirected directly to the Account Page. The data was saved but I could reach neither preview page nor confirmation page.

Can somebody explain this? Oswaldo and I are trying to take screen shoots of all the webpages.

Thanks
Ardhi

**Comment by BujakiAttila** [comment]
Thanks for the notice. Since it is a diffent issue, I am going to open a new ticket for this.

**Comment by Legend-Dale** [comment]
When you are logged in you are redirected to the account page.

When you are not logged in you get to review you data (employee side).

The preview and confirmation page are actually only for the employee, not
the employer.
