### ISSUE TITLE
"Remark"-messages are currently being ignored in the html generation

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#108]
There are additions to the data fields such as

EMPLOYEE.placeOfBirth.remark= (only if without insurance number)
EMPLOYEE.birthDate.remark= (DD/MM/YYYY)
and so on.

They should be added in the html form generation.

**Comment by BujakiAttila** [comment]
Why don't we add them simly to the captions? I don't really see why should they be separated.

**Comment by Legend-Dale** [comment]
There are only needed in the employee/edit file. But the field names are also used for other purposes e.g. the pdf generation or the dashboard...

**Comment by Legend-Dale** [comment]
I have removed the remarks from the labels and added them in the placeholder messages.
