### ISSUE TITLE
EmployeeList - multi-lingual support

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#11]
The EmployeeList ViewTemplate is not supporting multiple languages.

This should be implemented. The static strings should be replaced by the dynamic content.

th:text="#{employee.maritalStatus}"

**Comment by JonasGroeger** [comment]
Isn't that fixed as of now?

**Comment by BujakiAttila** [comment]
As far as I know yes. The enums are also fixed?

**Comment by JonasGroeger** [comment]
Yup. Instead of english they have referenxes to messages_xx.properties now

**Comment by BujakiAttila** [comment]
Let's still take a look and close this issue when all the stuffi OK in this ViewTemplate.

**Comment by Legend-Dale** [comment]
Generally this is done. There is only one thing: When the page is set German the name field is "Neuer Mitarbeiter", in English it is "New Employee". Should we leave it like this? Making it dynamic is not trivial, I believe.

**Comment by JonasGroeger** [comment]
Right now, this is statically defined in the code. We might want to make a lookup on that one. Its kind of easy but I dont know how that works right now :)

**Comment by BujakiAttila** [comment]
Looks OK for me. I am going to close the issue.

![image](https://cloud.githubusercontent.com/assets/2914096/8021585/5ca714ae-0ca5-11e5-83bd-6c940e4d8277.png)

![image](https://cloud.githubusercontent.com/assets/2914096/8021590/78942a8a-0ca5-11e5-9d5c-7ad8d84fabb0.png)
