### ISSUE TITLE
Include library licenses and copyrights

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#13]
Based on the output of Issue #1 , maybe we should includ license info and copyrights.

What do you think?

**Comment by JonasGroeger** [comment]
I think thats a good thing to do for the final release.

**Comment by BujakiAttila** [comment]
Aren't we bounded by the law to include them already in any release?

**Comment by JonasGroeger** [comment]
I guess :)

**Comment by BujakiAttila** [comment]
Should we include them in the midterm relase or just at the end of the semester?

**Comment by JonasGroeger** [comment]
We should do that at the end of the semester since the libraries are final then.

**Comment by BujakiAttila** [comment]
Do you know which license file should be uploaded? I am not sure anymore.
