### ISSUE TITLE
Evaluate WebJars (as replacement for manual static asset dependency management)

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#17]
Currently, we use the folder [`src/main/resources/static`](https://github.com/JOBAA/amos-ss15-proj4/tree/master/src/main/resources/static) as our repository for static resources such as JavaScript, Stylesheets, Images and Fonts. They have to be manually updated. Yes there are some tools to do dependency management for those static resouces. However, [they are not Java based](http://bower.io/). 

Then, [there are WebJars](http://www.webjars.org/documentation). They can handled like regular libraries by putting them into the `build.gradle` file. When there is an update, just update the version in the `build.gradle` file and they get pulled in automagically, just like our other dependencies.

Its something neat we can consider when we try to make our project clean.

**Comment by BujakiAttila** [comment]
Could you be more precise? I don't really understand what is this about, Thanks!

**Comment by JonasGroeger** [comment]
Currently, we use the folder [`src/main/resources/static`](https://github.com/JOBAA/amos-ss15-proj4/tree/master/src/main/resources/static) as our repository for static resources such as JavaScript, Stylesheets, Images and Fonts. They have to be manually updated. Yes there are some tools to do dependency management for those static resouces. However, [they are not Java based](http://bower.io/). 

Then, there are WebJars. They can handled like regular libraries by putting them into the `build.gradle` file. When there is an update, just update the version in the `build.gradle` file and they get pulled in automagically, just like our other dependencies.

Its something neat we can consider when we try to make our project clean.

**Comment by BujakiAttila** [comment]
Thanks. Sounds nice. I think we could use something like this. Currently I am pretty busy with learning about UI/Integration testing, but later I could take a look into this. Anybody else?

**Comment by BujakiAttila** [comment]
Still under evaulation? Do we really need this? Would be nice. But I think we should stick to a minimal set we do really need.

Oppinions?

**Comment by BujakiAttila** [comment]
I am going to close this issue, since we have currently other tasks to work on. In the future such option could be useful, but currently it is way out of reach.
