### ISSUE TITLE
Rename EmployeeLogin page

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#32]
I think the EmployeeLogin page is not appropriate. I suggest to change it. This page is mainly used by clients and not by Employees.

Am I right? Employees should use their tokens to access the EmployeeForm. The Login with username and password is for the administrators of the system. Am I right?

What do you think?

**Comment by sutard** [comment]
Attila is right. Access to the questionnaire for the Employee is only granted if he or she has the token from Clients.

In the other hand, Clients will use username and password for loggin in.


Thanks
Ardhi

**Comment by BujakiAttila** [comment]
This rename won't be visible on the Web pages, but is going to help us during the development process. Using appropriate names can boost up our performance.

Thanks for the quick feedback.

**Comment by nikithamohan** [comment]
Will rename it.

**Comment by BujakiAttila** [comment]
Please make sure that everything works after the rename. Now I have fixed the Login process and the related user stories are implemented. Thank you.

**Comment by Matombo** [comment]
refactoring done

**Comment by nikithamohan** [comment]
Hi,

Error message: error creating bean with name ' employeeFormController'

Error message: error creating bean with name ' employeeRepository'

Error message: error creating bean with name 'entityManagerFactory'

Error message: failed to execute SQL script statement in data.sql

Error message: duplicate key value violates unique constraint "client_pkey"

Could anybody please help me with this. I did change to the test profile.

Thanks,
Nikitha.

**Comment by JonasGroeger** [comment]
@nikithamohan Is this a separate issue or why is this in this closed Issue? Pleaes provide us with a Stacktrace. What did you already try to debug this?

**Comment by nikithamohan** [comment]
I did find the BeanDefinitionValue file. But did not know what to do
further.
Please find the attachment for the stacktrace.

**Comment by JonasGroeger** [comment]
Please open a separate issue. Also I cant find a stacktrace attached. This way I cant help you.

**Comment by nikithamohan** [comment]
Hi POs,

Could you please let me know the drop down fields for the field-type of
fixed-term contract under the Befristung/Temporary Employment section? I am
not able to find a description for it in the reference file.

Thanks,
Nikitha

**Comment by sutard** [comment]
Can you please give me the screenshot of the drop down field?

Thanks
Ardhi

**Comment by nikithamohan** [comment]
The drop down menu items of the Type of Fixed-term contract field? In the
Befristung/Temporary Employment section?

**Comment by sutard** [comment]
Exactly my excel (mac) cannot run the macro. I can’t see the contains of the drop down list. Just send me the screenshot and I’ll help you to find the information you need.

Cheers
Ardhi



> Am 01.07.2015 um 00:10 schrieb nikitha mohan <notifications@github.com>:
> 
> The drop down menu items of the Type of Fixed-term contract field? In the
> Befristung/Temporary Employment section?
>

**Comment by nikithamohan** [comment]
Hey ardhi,

Please find the attachment.

**Comment by sutard** [comment]
Hi Nikitha,

I found no attachment :'(





> Am 01.07.2015 um 00:27 schrieb nikitha mohan <notifications@github.com>:
> 
> Hey ardhi,
> 
> Please find the attachment.
> 
>

**Comment by nikithamohan** [comment]
Hey ardhi,

Can you please check now? I have attached it again.

**Comment by sutard** [comment]
still nothing nikitha :(




> Am 01.07.2015 um 02:52 schrieb nikitha mohan <notifications@github.com>:
> 
> Hey ardhi,
> 
> Can you please check now? I have attached it again.
>

**Comment by nikithamohan** [comment]
Can you please check Your Facebook? I have sent it there😁

**Comment by nikithamohan** [comment]
Hi,

Please ignore the commits carrying the name "changes". It was a mistake.
Sorry!

Nikitha

**Comment by nikithamohan** [comment]
Implemented #67-Entlohnung/Remuneration

https://github.com/JOBAA/amos-ss15-proj4/commit/cb78a29ba1a98cfcaf51e19f98843445051934d4

**Comment by osanbehi** [comment]
[image: Inline image 1]
