### ISSUE TITLE
Database access EmployeeForm, EmployeeReview, EmployeeSubmit

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#33]
On my system (Windows 8.1), when I fill out data into the EmployeeForm, it is not stored in the database.
When reaching the EmployeeSubmit page, the id is null.
Downloading the files fails. 
It's surely only a small issue, since the EmployeeEdit page works fine.

**Comment by JonasGroeger** [comment]
What did you already do to debug the problem? Maybe setting a breakpoint in the /EmployeeSubmit page?

**Comment by Legend-Dale** [comment]
It works without error after the commit 27/07/15 11:04, but the data is not stored in the database open in EmployeeList.
I have checked my databases and my guess is that it is not saved at all.

**Comment by JonasGroeger** [comment]
This is solved after todays developer meeting, right @Legend-Dale ?

**Comment by Legend-Dale** [comment]
The problem was that no client was assigned. Currently it is always client 1. I did this fix today. 
When you do the session management, don't forget to change that in the EmployeeSubmit controller.

**Comment by JonasGroeger** [comment]
Can you point me to the commit where you changed that?

**Comment by Legend-Dale** [comment]
Sorry, that is part of my commit from the 31 May "Removed ambiguity or EmployeeReview...."
I fixed that while I was working on feature 36.

**Comment by JonasGroeger** [comment]
You can reference commits by using their SHA1 Hash (or a part of it) like this:

`68f7693` -> 68f7693e63f37dcbb3f60103a6385566e824d90b
`68f7693e63f37dcbb3f60103a6385566e824d90b` -> 68f7693e63f37dcbb3f60103a6385566e824d90b

**Comment by Legend-Dale** [comment]
Thanks, I'll do that next time.

**Comment by BujakiAttila** [comment]
:+1:
