### ISSUE TITLE
New Employee doesn't work in course console

### ISSUE THREAD

**Issue by Matombo** [JOBAA/amos-ss15-proj4#34]
someone can reproduce it? maybe i have done something wrong with setting up the database

**Comment by JonasGroeger** [comment]
I cant reproduce it. Can you give me some more details please? "doesn't work" isnt really an appropriate bug report for a developer. Did you look at the log output?

**Comment by Matombo** [comment]
well after reuploading i couln't reproduce it myself so strange bug being strange
(but that i dosn't work ocationally like in the presentation is still there)
