### ISSUE TITLE
Project fails to start with non empty database

### ISSUE THREAD

**Issue by Matombo** [JOBAA/amos-ss15-proj4#35]
Frist time it's startet the example employees are added.
2nd time it's started they are added again but their id's allready exists so the application crashes

**Comment by JonasGroeger** [comment]
As expected. I explained it in the developer meeting on thursday. Its because every time the application is started, the file `data.sql` is loaded into the database for easy testing.

**Comment by Matombo** [comment]
for information:
you can set spring.datasource.initialize=false which prevents data.sql from beong loaded by the means mentioned in this doc: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html

**Comment by JonasGroeger** [comment]
You can put that in your dev specific settings.
Am 31.05.2015 17:25 schrieb "Werner" <notifications@github.com>:
