### ISSUE TITLE
'Download as text' function throws an unexpected exception.

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#38]

**Comment by Legend-Dale** [comment]
Download as PDF works still.

**Comment by JonasGroeger** [comment]
"Throws an error" isn't exactly precise. Debug it and provide details here.

**Comment by Legend-Dale** [comment]
Works again after yesterdays commit.

**Comment by Legend-Dale** [comment]
I just wanted to open an issue so that you all know there is a bug. 
If I start debugging it, I can right away fix it, can't I?

**Comment by JonasGroeger** [comment]
Yes of course
Am 02.06.2015 15:20 schrieb "Benedikt Rauh" <notifications@github.com>:

**Comment by Legend-Dale** [comment]
One gets the error message "EmployeeTextFileDownload not found". 
It happens, when the String "fileContent" is written to the ServletOutputStream:
out.println(fileContent);
Since the issue sometimes occurs, sometimes not, it may be an encoding problem. 
As part of feature 45 I will rewrite the code anyway and hopefully the error doesn't occur again.
We have the solve the encoding issue, though...

**Comment by BujakiAttila** [comment]
Is this resolved now?

**Comment by BujakiAttila** [comment]
It was working for me. How can you reproduce this error? Plese provide details, so I can make sure that it is resolved or it is still an issue. Thank you!

**Comment by Legend-Dale** [comment]
Login and click on download as text in the dashboard.

**Comment by BujakiAttila** [comment]
It is fixed then, rigth? For me it was working, and based on your comment you agree. I close this issue then. Thank you.
