### ISSUE TITLE
Clean up the HTML

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#39]
The current HTML is a huge mess:

* Duplicated code everywhere
* Inconsistent indentation

Whenever there is a merge conflict, its a PITA to merge. Thus, we should

1. Use consistent 4 spaces of indentation everywhere. You can convert pages [either here](http://jsbeautifier.org) or using you most favorite tool (i.e. Eclipse or alike).
2. We should consider using [Thymeleafs Template Layout](http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#template-layout). Its really easy to understand. We could have a header and a footer file that will always be included in every page. Nice! This way we have lost a lot of duplicated code. Anybody wanna remove some code :)?

**Comment by BujakiAttila** [comment]
I am going to clean up the ViewTemplates tomorrow. I have already started it, but I was not really concentration on it. Just removed some code duplication and introduced the usage of templates(as you mentioned in the second point).

**Comment by BujakiAttila** [comment]
Started.... #58 

There is still lot to do.

**Comment by BujakiAttila** [comment]
I think it is good enough for now. I have changed indentation to spaces instead of tabs, and introduced templating where it was possible.
