### ISSUE TITLE
ViewTemplate - RegistrationPage - Properly bind client instance and HTML form fields

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#41]
Currently the fields in the HTML form are not binded properly to the Client object's fields.
The necessary fields are not yet implemented.
The following data fields should be added to the Client class:
 - Title
 - First name
 - Last name
 - Birthdate
 - Office number
 - Phone numbe
 - Company type
 - Country
 - Street name
 - ZIP code
 - Password (Hash?)

Some fields are already added like: Email and Company name. All the fields on the Registration view should have their fields in the Client class. Currently only few from these are implemented.

**Comment by JonasGroeger** [comment]
Do we really need that many details?

**Comment by BujakiAttila** [comment]
I don't think so, but just take a look at the user story 38' acceptance criteria:

> "In the Registration Page, the client should enter the information categorized as follows:
> Main Data
>  Title: Mr./ Mrs./ Ms. - First name(s): - Last name: -  Birthday (dd/mm/yyyy): - Phone number (office): > - Mobile number (optional):
>
> Company Details
>   Company name: - Company type: - Country: - Street name/ house number: - Zip code:
>
> Login Data
>   Company email: (used then as username) - Password: - Confirm password:"

So.... I think yes. Do you have any suggestions?

**Comment by BujakiAttila** [comment]
The registration and edit client fields are properly implemented now. I am going to close this issue.
