### ISSUE TITLE
Implement login screen messages

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#46]
Informational messages should be displayed on the login page on different events.

For example:
 - Registration done (?registered)
 - Email confirmed (?confirmed)
 - Email confirmation failed (?confirmfail)
 - Wrong credentials entered (?error)

Each of these events are already easy to detect from the query string. For each of these there is a special query parameter added. These are visible after the examples in brackets.

**Comment by JonasGroeger** [comment]
Could be done with flash messages: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/mvc/support/RedirectAttributes.html

**Comment by BujakiAttila** [comment]
Done; implemented using query string params. Later we could improve this solution.
