### ISSUE TITLE
Agree on Coding Guidelines

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#49]
(no description)

**Comment by Matombo** [comment]
template naming example:
folder | filename
client/ dashboard
          login
          register
          profile
employee/ token
                 form
                 preview
                 confirm

**Comment by BujakiAttila** [comment]
Werner (Matombo), are you sure that you wanted to post this comment to this topic?

**Comment by BujakiAttila** [comment]
To clarify what is this issue about:

We should agree on a coding standard and start using a tool that forces us to keep the code quality in this aspect on an appropriate level, and to comform the predefined set of rules.

**Comment by Matombo** [comment]
well i thought since no comment was given it's general about how the source code should look like, that includes file naming

**Comment by BujakiAttila** [comment]
We should also discuss the naming issue. That is true. But maybe let's open a different issue for that.

**Comment by Matombo** [comment]
just to write down what we have discused last week:

class
{
    method
    {
        if {
        }
        else {
        }
    }
}

**Comment by Matombo** [comment]
messages files:
CONSTANT.valueName
fileName.valueName
