### ISSUE TITLE
Renaming and reordering java files

### ISSUE THREAD

**Issue by Matombo** [JOBAA/amos-ss15-proj4#54]
after renaming and reordering the template structure we could do it for the java files also

to start i would:
rename EmployeeFormControler to EmployeeController
rename LoginFormControler to LoginController or merge it with ClientController

ps why has CurrentClientControlerAdvice such a long an unhandy name + should we place it in util?

**Comment by BujakiAttila** [comment]
Are there any naming guidelines available for Spring Controllers and ViewTemplates? I think we should be trying to conform to the naming conventions in use.

I think as a first step we should find such conventions, agree on what we want to use, then create a full plan for the renaming. We should do it smart, so it could be so for a while. For now I am ok with these names though, but in the long run we should go for some smarter naming and organization system.

**Comment by JonasGroeger** [comment]
I did some research. It turns out that there are not really any naming conventions regarding these. Like @Matombo, I would also like to have

```
EmployeeFormController -> EmployeeController
LoginFormController    -> LoginController
```

Just rename them :)

**Comment by BujakiAttila** [comment]
We have agreed how to restructure things and the needed steps had been done.

In the future we will still need such activities, but for now I am going to close the issue, since we have discussed it and agreed on a current soltuion.
