### ISSUE TITLE
Create tests for already implemented functionality

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#57]
The current level of test covarage is not acceptable. We should start writing tests for the functionality that is already in place, so we could use our automated test cases to check them.

Anybody up for the task?

**Comment by Matombo** [comment]
Do we have integration testing in place by now?

**Comment by BujakiAttila** [comment]
We have a single integration test implemented:
[In this file(]https://github.com/JOBAA/amos-ss15-proj4/blob/master/src/test/java/de/fau/amos4/test/integration/ClientControllerTest.java)

We should keep on implementing more.

**Comment by BujakiAttila** [comment]
We have taken the necessary steps, keep on doing implementing new test cases, but the team is on the right path, writing test cases for new and previously implemeneted functionality so I close this issue now.
