### ISSUE TITLE
Footer is not displayed properly

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#59]
The footer is not displayed properly after introducing templates. The problem has occured on the registration page.

Picture:
![image](https://cloud.githubusercontent.com/assets/2914096/8023130/c44fc27a-0cfc-11e5-96b2-a74b0444b1f8.png)

Could somebody fix this?

**Comment by Legend-Dale** [comment]
This is fixed, isn't it?

**Comment by BujakiAttila** [comment]
On login screen it is OK now. But the registration screen is not displayed well for me on Chrome (43.0.2357.81 m).

All I did is just click the registration button on the login screen for clients.

![image](https://cloud.githubusercontent.com/assets/2914096/8064765/29fc41c0-0edd-11e5-91b6-604a2200bc5c.png)

**Comment by Legend-Dale** [comment]
I guess I can fix that.

**Comment by BujakiAttila** [comment]
Thank you. :+1:  Please send feed back if you have made it.

**Comment by Legend-Dale** [comment]
Done.
