### ISSUE TITLE
Employee form - Submit - Parameters in URL

### ISSUE THREAD

**Issue by BujakiAttila** [JOBAA/amos-ss15-proj4#61]
I have noticed that the Employee data is passed in the URL when submitting the form data on the preview form.

Do we really want to do it like this?

![image](https://cloud.githubusercontent.com/assets/2914096/8042161/919e3736-0e1d-11e5-92bd-af88d938c966.png)

**Comment by Legend-Dale** [comment]
Is this a problem?

**Comment by BujakiAttila** [comment]
I think it is not that practical and not that good. Maybe you disagree, that's why I formulated it as a question. "Do we really want to do it like this?" I think it doesn't look good and would be better to POST the form data.

**Comment by BujakiAttila** [comment]
We have agreed to leave it like this.
