### ISSUE TITLE
Language buttons 

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#71]
We cannot simply add the language buttons on every html page as a template.

edit requires e.g. an id passed as an argument in the address line, employee preview requires a token.

The pages crash when trying to change the language (because of missing parameters).

What would be the best way to deal with that?

**Comment by JonasGroeger** [comment]
The best way to deal with that would be to have an input wizard that asks for a language at the very beginning. After that, no more switching languages is allowed.

**Comment by Legend-Dale** [comment]
Yes, this or a menu entry to switch languages. Maybe among the profile data.
Shouldn't be too much of an effort, anyway.

**Comment by JonasGroeger** [comment]
The menu entry would be good for the client side.

**Comment by BujakiAttila** [comment]
Now the language buttons are removed from some pages and not shown everywhere. I am think this issue can be closed now, since we have discussed it and took the necessary steps.
