### ISSUE TITLE
Posters

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#74]
We should start thinking about the posters as soon as possible. 
We need the content and we need the design. 
I am not very good at this (especially the design), but I could write down some bullet points for the content.

Where should we do our group picture? I can bring my digital compact camera, but we need another photographer.

**Comment by BujakiAttila** [comment]
I think this is done as planned. I am going to close this issue, since we have already submitted the poster and also have the group pictures.
