### ISSUE TITLE
Company name

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#75]
Use this tread for suggestions and discussion.

After we have some good suggestions we can make a vote on them.

**Comment by JonasGroeger** [comment]
I vote for 'Kraftkonzentrat' :)

**Comment by nikithamohan** [comment]
Means power?

**Comment by Legend-Dale** [comment]
Some suggestions:
ARTOP (A random team of Programmers)
ELMEM (Everyone likes Mate, except Matombo)
BAC      (Best AMOS company)
AGORP (Awesome Groud Of Random People)
Jonas AG
Ercom (Company Erlangen)
Amosta (AMOS startup)
Starmos (Startup AMOS)

**Comment by Legend-Dale** [comment]
I think Excellinator sounds like a super hero...

**Comment by nikithamohan** [comment]
I like AGORP (Awesome Groud Of Random People) but how about P for
programmers ;)

**Comment by Matombo** [comment]
i vote for ELMEM ^^

**Comment by BujakiAttila** [comment]
HardCoders Inc. ?

**Comment by Legend-Dale** [comment]
Our name will be Jowbana.

**Comment by sutard** [comment]
Do we have the logo already?
