### ISSUE TITLE
Client registration form: Gender important?

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#77]
Hey @sutard & @osanbehi 

Is the the gender under `/client/register` important? I don't think so.

**Comment by sutard** [comment]
Do you mean the Title Mr. Mrs. or Ms.? Does it affect something?

**Comment by JonasGroeger** [comment]
No, not really. But its completely unnessecary. Same for `date of birth`.

**Comment by sutard** [comment]
We think that both fields are still necessary for administrative purposes in the future. You sometime cannot identify whether a certain name from a certain country is female or male name.

As far as we know, all web/online services are required to comply to Federal Trade Commission regarding Children’s Online Privacy Protection Act that:
„…any person who operates a website located on the Internet or an online service and who collects or maintains personal information…. “
must not be under the age of 13.

Thanks
Ardhi

**Comment by BujakiAttila** [comment]
Thank you for the feedback. The fields are there as wanted. I am closing the issue now, since it is already resolved.

**Comment by JonasGroeger** [comment]
We don't really have to comply with COPPA.
