### ISSUE TITLE
Employee.java - do we need toString(), equals(), and hashCode()?

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#79]
Do we need all of the three functions? 

toString() is not used any more for example. 

I ask because is requires some effort to keep these functions up-to-date.

**Comment by Legend-Dale** [comment]
We need equals, that's obvious.

http://eclipsesource.com/blogs/2012/09/04/the-3-things-you-should-know-about-hashcode/
[15:53:28] Jonas Gröger: Whenever you implement equals, you MUST also implement hashCode

**Comment by JonasGroeger** [comment]
I don't think we use the functions `equals` or `hashCode` anywhere. The `toString` function should however be kept.

**Comment by Legend-Dale** [comment]
As long as we can auto-generate them, they definitely don't hurt. 
I thought it would be unnecessary work to keep them up to date...

**Comment by JonasGroeger** [comment]
I guess thats done then.
