### ISSUE TITLE
Decouple Request Logic from Business functionality.

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#9]

**Comment by JonasGroeger** [comment]
(maybe with a facade?)

**Comment by BujakiAttila** [comment]
I am going to take a few steps in this topic.
 * EmployeeFormController - EmployeeDownloadZip: Extract Archive and PDF document management into a separate class
* PrintDataController - EmployeeZipFileDownload: Is also containing too much functionality. This should be places into specific classes.

Any more ideas?

**Comment by BujakiAttila** [comment]
I set this issue to closed, since we got different tasks from out product owners. We are going to focus on implementing the remaining user stories instead of bigger scale refactoring.
