### ISSUE TITLE
Missing messages for Employee fields and broken dropdown messages

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#92]
As long as there is a broken message, submit on the edit form doesn't work (which is currently the case because of some broken dropdowns).

Messages for the Employment Section are missing.

Messages and format of dropdown fields is broken.

**Comment by JonasGroeger** [comment]
That seems like three issues for me.

**Comment by BujakiAttila** [comment]
I am taking care of the missing messages and also trying to do something about the error messages when invalid formatted data is submitted. This last is going to be a bit trickier, but I think it is going to be also OK.

**Comment by Legend-Dale** [comment]
It seems all labels for data fields are there.

I have fixed the broken data fields of the denomination dropdown field.

Messages for empty fields are generated automatically now.

Messages for invalid fields have to be meaningful. 
Instead of "invalid fields", we should have messages like "No special characters allowed" or "field must be 12 characters long"...

**Comment by BujakiAttila** [comment]
Yes. It would be nice to include some more information. For a starter I just wanted to add something instead of having a missing message, but yes, of course. Adding a descriptive error message, with more information would be very nice.

**Comment by Legend-Dale** [comment]
I have added invalid fields messages for every field.

They are very crude, but I don't think we have time to make them better now.
